global:
  scrape_interval: 15s # How often to fetch metrics
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kyc_service'
    static_configs:
      - targets: ['kyc_service:5001']

  - job_name: 'pan_service'
    static_configs:
      - targets: ['pan_service:5002']

  - job_name: 'aadhaar_service'
    static_configs:
      - targets: ['aadhaar_service:5003']